Algoritmo "circulo"
// Disciplina   : [Linguagem e Lógica de Programação - Curso Udemy]
// Data atual  : 18/01/2024
Var
// Seção de Declarações das variáveis 
    r, area : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreva("Digite o valor do raio do circulo: ")
     leia(r)
     
     area <- pi * r * r
     
     escreval("AREA =  ", area:8:3)

Fimalgoritmo