Algoritmo "Notas"
// Disciplina   : [Algoritmos e Lógica de Programação-O Curso COMPLETO]
// Data atual  : 12/01/2024
Var

    nota1, nota2, notaFinal : real

Inicio
     escreva("Digite a primeira nota: ")
     leia(nota1)
     escreva("Digite a segunda nota: ")
     leia(nota2)
     
     notaFinal <- nota1 + nota2
     
     escreval("Nota Final= ", notafinal:5:1)
     
     se notaFinal < 60 entao
       escreval("REPROVADO")
     fimse

Fimalgoritmo