Algoritmo "soma"
// Disciplina   : [Linguagem e Lógica de Programação - Curso Udemy]
// Data atual  : 16/01/2024
Var
// Seção de Declarações das variáveis 
 x, y, soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreva("Digite o valor de X: ")
     leia(x)
     escreva("Digite o valor de Y: ")
     leia(y)
     
     soma <- x + y
     
     escreval("SOMA =  ", soma)
Fimalgoritmo